from typing import Any
import json
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from executors.python_executor import execute_python


async def execute_output(script: str, input_data: Any) -> Any:
    """
    Execute output visualization by calling python executor with the script and input data.

    The script should accept data via sys.argv[1] as JSON (generated by generate_python_executable).

    Args:
        script: Python script that accepts JSON data via sys.argv[1]
        input_data: Actual results from previous executables (dict with executable_id keys)

    Returns:
        Execution result from python executor
    """
    try:
        # Call python executor with script and input data
        result = await execute_python(script=script, input_data=input_data)
        return result

    except Exception as e:
        raise Exception(f"Output execution error: {str(e)}")
